### ISSUE TITLE
Use different color for different categories

### ISSUE THREAD

**Issue by nojaf** [fable-compiler/community#11]
I would like different colors for `tool` than `library`.
![image](https://user-images.githubusercontent.com/2621499/63491200-df3e3a00-c4b6-11e9-87e9-562c24fc4f85.png)
Want to do a PR myself, just asking your opinion on this.

**Comment by MangelMaxime** [comment]
I do agree that having different color would make it clearer :)

**Comment by alfonsogarciacaro** [comment]
Makes sense, could you please send a PR to set the color here? https://github.com/fable-compiler/community/blob/445119b85bfb749296586f5d564b5563342b616d/src/App.fs#L115
